name: Generate documents

on:
  push:
    branches: [ main ]

jobs:
  docs:
    name: Generate documents
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generating documents
        uses: obaland/panvimdoc@main
        with:
          vimdoc: vfiler
          description: File manager plugin for Vim/Neovim
          pandoc: doc/vfiler.md
          toc: true
      - name: Update doucments
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update doc/vfiler.txt'
          branch: ${{ github.head_ref }}
